### PR TITLE
Update to protocol version 2

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by jasongrout** [comment]
Were the docs sufficient? https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/schema/messages.md#widget-messaging-protocol-version-2

**Comment by jasongrout** [comment]
Also, what would you think of changing the schema to have a single string version field, rather than `version_major` and `version_minor`? Then we could express things like dev versions, prerelease versions, patch versions, etc.

**Comment by SylvainCorlay** [comment]
I think that everything went fine. The big item that I need to complete is the support for binary buffers in xeus, then in xwidgets.

**Comment by SylvainCorlay** [comment]
A version string is fine. We have tools to manipulate them.

Do you think that xwidgets should be solit into core / controls from the start?

**Pull request merged**
